refactor: const-qualify TokenParam constructors
jarimayenburg/fhir-sdk pull request #8
Opened 2024-08-08 07:20 UTC by adammozes

2024-08-08 09:02 UTC, jarimayenburg approved these changes

2024-08-08 09:04 UTC, jarimayenburg requested changes
If you're going to do this for `TokenParam`, why not do it for the other search param types too?

2024-08-29 23:04 UTC, jarimayenburg commented
@adammozes Do we want to follow up on this or is it no longer necessary?

2024-08-30 07:15 UTC, adammozes commented
We can close this one, it isn't urgent to build TokenParams in a const environment anymore.

2024-08-30 07:15 UTC, closed without merging